// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Infrastructure;

#nullable disable

namespace ShoppingCart.Infrastructure.Migrations
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20230218175007_UserTable")]
    partial class UserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Comments.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Comment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "very good my friend",
                            ProductId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Content = "im no like",
                            ProductId = 2L
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "purses",
                            CreatedAt = new DateTime(2023, 2, 18, 19, 50, 7, 745, DateTimeKind.Local).AddTicks(7182),
                            Description = "pretty purse",
                            Name = "Purse",
                            Photo = "photo.jpeg",
                            Price = 111.99m,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Category = "scarfs",
                            CreatedAt = new DateTime(2023, 2, 18, 19, 50, 7, 745, DateTimeKind.Local).AddTicks(7216),
                            Description = "blah",
                            Name = "Scarf",
                            Photo = "scarf.jpeg",
                            Price = 300.99m,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 2, 18, 19, 50, 7, 747, DateTimeKind.Local).AddTicks(9405),
                            Email = "pesho@pesho.be",
                            FirstName = "Pesho",
                            LastName = "Peshov",
                            Password = "ne kazvai na nikoi",
                            Phone = "12345678",
                            UserName = "pesho_boga"
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Comments.Comment", b =>
                {
                    b.HasOne("ShoppingCart.Domain.BoundedContext.Products.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Products.Product", b =>
                {
                    b.HasOne("ShoppingCart.Domain.BoundedContext.Users.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Users.User", b =>
                {
                    b.OwnsOne("ShoppingCart.Domain.BoundedContext.Users.ShoppingCart", "ShoppingCart", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("ShoppingCartCreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ShoppingCartCreatedAt");

                            b1.Property<decimal>("TotalAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner("User")
                                .HasForeignKey("UserId");

                            b1.Navigation("User");

                            b1.HasData(
                                new
                                {
                                    UserId = 1L,
                                    ShoppingCartCreatedAt = new DateTime(2023, 2, 18, 19, 50, 7, 747, DateTimeKind.Local).AddTicks(8649),
                                    TotalAmount = 0m
                                });
                        });

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Products.Product", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ShoppingCart.Domain.BoundedContext.Users.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
